[project]
name = "rq-rediscron"
description = "Redis-backed runtime-editable cron scheduler for RQ"
readme = "README.rst"
requires-python = ">=3.10"
license = "MIT"
authors = [
    {name = "Stefan Berder", email = "code@measureofquality.com"},
]
maintainers = [
    {name = "gams monitoring", email = "code@measureofquality.com"},
]
keywords = ["rq", "redis", "cron", "scheduler", "jobs"]
classifiers=[
    'Development Status :: 4 - Beta',
    'Environment :: Console',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Programming Language :: Python :: 3.14',
]
license-files = ["LICENSE"]
dependencies = [
    "redis>=5",
    "rq>=2.8",
]
dynamic = ["version"]

[project.urls]
Homepage = "https://github.com/gams/rq-rediscron"
Repository = "https://github.com/gams/rq-rediscron"
Documentation = "https://rq-rediscron.readthedocs.io/en/latest/"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["rediscron"]

[tool.hatch.build.targets.sdist]
exclude = ["docs*", "tests*", "foo_*"]

[tool.hatch.version]
path = "rediscron/__meta__.py"

[dependency-groups]
dev = [
    "ruff>=0.15.15",
    "tox>=4.55.0",
    "tox-uv>=1.35.2",
]
docs = [
    "shibuya>=2026.5.19",
]
