[tox]
envlist = py310
skip_missing_interpreters = true

[testenv]
runner = uv-venv-lock-runner
description = test description
dependency_groups =
    dev
commands =
    python -m unittest discover -s tests
